# Generated by Django 4.1.2 on 2022-11-27 17:20

from django.db import migrations, models
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='training',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=training.models.upload_to),
        ),
        migrations.AlterField(
            model_name='tag',
            name='training',
            field=models.ManyToManyField(related_name='tags', to='training.training'),
        ),
    ]
