# Generated by Django 4.1.2 on 2022-11-28 14:29

from django.db import migrations, models
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_duration_training_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='image_url',
            field=models.ImageField(blank=True, default='training/deault.png', upload_to=training.models.upload_to),
        ),
    ]
