# Generated by Django 4.1.2 on 2022-11-28 17:50

from django.db import migrations, models
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='image_url',
            field=models.ImageField(blank=True, default='training/default.png', upload_to=training.models.upload_to),
        ),
    ]
